model: 
    num_segments: 8
    embed_dim: 128
    num_heads: 2
    num_layers: 1
    num_groups: 2
    actv_mode: elu
    pool_mode: mean
    k_size: [13, 3]
    hid_dim: [64, 64]
    num_classes: 1


training:
    num_epochs: 50
    num_batch: 32
    learning_rate: 5e-4
    optimizer: Adam
    exlr_on: False