model: 
    num_segments: 16
    embed_dim: 128
    num_heads: 2
    num_layers: 1
    num_groups: 1
    actv_mode: elu
    pool_mode: mean
    k_size: [13, 5]
    hid_dim: [32, 32]
    num_classes: 3

training:
    num_epochs: 50
    num_batch: 32
    learning_rate: 1e-4
    optimizer: Adam
    exlr_on: False